default: &default
  endpoint: 'https://acme-v01.api.letsencrypt.org/'
  email: 'upstill@gmail.com'

  # in Rails.root, path to private key
  private_key: 'key/keyfile.pem'

  # in Rails.root, path where certificates
  # will be stored (on Heroku this variable is ignored)
  output_cert_dir: 'certificates'

  # in Rails.root, path where challenge token
  # will be stored in case when DB will not be used
  challenge_dir_name: 'challenge'

production:
  <<: *default
  domain: 'strong-galaxy-5765.herokuapp.com'

staging:
  <<: *default
  domain: 'staging.recipepower.com'

development:
  <<: *default
  domain: 'local.recipepower.com'

test:
  <<: *default