require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MercuryPagesController do

  # This should return the minimal set of attributes required to create a valid
  # MercuryPage. As you add validations to MercuryPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MercuryPagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mercury_pages as @mercury_pages" do
      mercury_page = MercuryPage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mercury_pages).should eq([mercury_page])
    end
  end

  describe "GET show" do
    it "assigns the requested mercury_page as @mercury_page" do
      mercury_page = MercuryPage.create! valid_attributes
      get :show, {:id => mercury_page.to_param}, valid_session
      assigns(:mercury_page).should eq(mercury_page)
    end
  end

  describe "GET new" do
    it "assigns a new mercury_page as @mercury_page" do
      get :new, {}, valid_session
      assigns(:mercury_page).should be_a_new(MercuryPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested mercury_page as @mercury_page" do
      mercury_page = MercuryPage.create! valid_attributes
      get :edit, {:id => mercury_page.to_param}, valid_session
      assigns(:mercury_page).should eq(mercury_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MercuryPage" do
        expect {
          post :create, {:mercury_page => valid_attributes}, valid_session
        }.to change(MercuryPage, :count).by(1)
      end

      it "assigns a newly created mercury_page as @mercury_page" do
        post :create, {:mercury_page => valid_attributes}, valid_session
        assigns(:mercury_page).should be_a(MercuryPage)
        assigns(:mercury_page).should be_persisted
      end

      it "redirects to the created mercury_page" do
        post :create, {:mercury_page => valid_attributes}, valid_session
        response.should redirect_to(MercuryPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mercury_page as @mercury_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        MercuryPage.any_instance.stub(:save).and_return(false)
        post :create, {:mercury_page => { "url" => "invalid value" }}, valid_session
        assigns(:mercury_page).should be_a_new(MercuryPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MercuryPage.any_instance.stub(:save).and_return(false)
        post :create, {:mercury_page => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mercury_page" do
        mercury_page = MercuryPage.create! valid_attributes
        # Assuming there are no other mercury_pages in the database, this
        # specifies that the MercuryPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MercuryPage.any_instance.should_receive(:update).with({ "url" => "MyText" })
        put :update, {:id => mercury_page.to_param, :mercury_page => { "url" => "MyText" }}, valid_session
      end

      it "assigns the requested mercury_page as @mercury_page" do
        mercury_page = MercuryPage.create! valid_attributes
        put :update, {:id => mercury_page.to_param, :mercury_page => valid_attributes}, valid_session
        assigns(:mercury_page).should eq(mercury_page)
      end

      it "redirects to the mercury_page" do
        mercury_page = MercuryPage.create! valid_attributes
        put :update, {:id => mercury_page.to_param, :mercury_page => valid_attributes}, valid_session
        response.should redirect_to(mercury_page)
      end
    end

    describe "with invalid params" do
      it "assigns the mercury_page as @mercury_page" do
        mercury_page = MercuryPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MercuryPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => mercury_page.to_param, :mercury_page => { "url" => "invalid value" }}, valid_session
        assigns(:mercury_page).should eq(mercury_page)
      end

      it "re-renders the 'edit' template" do
        mercury_page = MercuryPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MercuryPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => mercury_page.to_param, :mercury_page => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mercury_page" do
      mercury_page = MercuryPage.create! valid_attributes
      expect {
        delete :destroy, {:id => mercury_page.to_param}, valid_session
      }.to change(MercuryPage, :count).by(-1)
    end

    it "redirects to the mercury_pages list" do
      mercury_page = MercuryPage.create! valid_attributes
      delete :destroy, {:id => mercury_page.to_param}, valid_session
      response.should redirect_to(mercury_pages_url)
    end
  end

end
