require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReferentsController do

  # This should return the minimal set of attributes required to create a valid
  # Referent. As you add validations to Referent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all referents as @referents" do
      referent = Referent.create! valid_attributes
      get :index
      assigns(:referents).should eq([referent])
    end
  end

  describe "GET show" do
    it "assigns the requested referent as @referent" do
      referent = Referent.create! valid_attributes
      get :show, :id => referent.id.to_s
      assigns(:referent).should eq(referent)
    end
  end

  describe "GET new" do
    it "assigns a new referent as @referent" do
      get :new
      assigns(:referent).should be_a_new(Referent)
    end
  end

  describe "GET edit" do
    it "assigns the requested referent as @referent" do
      referent = Referent.create! valid_attributes
      get :edit, :id => referent.id.to_s
      assigns(:referent).should eq(referent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Referent" do
        expect {
          post :create, :referent => valid_attributes
        }.to change(Referent, :count).by(1)
      end

      it "assigns a newly created referent as @referent" do
        post :create, :referent => valid_attributes
        assigns(:referent).should be_a(Referent)
        assigns(:referent).should be_persisted
      end

      it "redirects to the created referent" do
        post :create, :referent => valid_attributes
        response.should redirect_to(Referent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved referent as @referent" do
        # Trigger the behavior that occurs when invalid params are submitted
        Referent.any_instance.stub(:save).and_return(false)
        post :create, :referent => {}
        assigns(:referent).should be_a_new(Referent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Referent.any_instance.stub(:save).and_return(false)
        post :create, :referent => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested referent" do
        referent = Referent.create! valid_attributes
        # Assuming there are no other referents in the database, this
        # specifies that the Referent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Referent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => referent.id, :referent => {'these' => 'params'}
      end

      it "assigns the requested referent as @referent" do
        referent = Referent.create! valid_attributes
        put :update, :id => referent.id, :referent => valid_attributes
        assigns(:referent).should eq(referent)
      end

      it "redirects to the referent" do
        referent = Referent.create! valid_attributes
        put :update, :id => referent.id, :referent => valid_attributes
        response.should redirect_to(referent)
      end
    end

    describe "with invalid params" do
      it "assigns the referent as @referent" do
        referent = Referent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Referent.any_instance.stub(:save).and_return(false)
        put :update, :id => referent.id.to_s, :referent => {}
        assigns(:referent).should eq(referent)
      end

      it "re-renders the 'edit' template" do
        referent = Referent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Referent.any_instance.stub(:save).and_return(false)
        put :update, :id => referent.id.to_s, :referent => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested referent" do
      referent = Referent.create! valid_attributes
      expect {
        delete :destroy, :id => referent.id.to_s
      }.to change(Referent, :count).by(-1)
    end

    it "redirects to the referents list" do
      referent = Referent.create! valid_attributes
      delete :destroy, :id => referent.id.to_s
      response.should redirect_to(referents_url)
    end
  end

end
