---
:root: bojongourmet.com
:selector: div.wprm-recipe
:trimmers:
- div.wprm-recipe-notes-container
- div.wprm-recipe-image
- div.wprm-call-to-action-text-container
- a.wprm-recipe-print
- a.wprm-recipe-pin
- a.wprm-recipe-jump
- div.wprm-recipe-rating
- div.wprm-container-float-right
:grammar_mods:
  :gm_bundles: :wordpress
  :rp_title:
    :in_css_match: h2.wprm-recipe-name
:sample_url: http://bojongourmet.com/2015/12/coffee-cinnamon-muscovado-sugar-flans-the-new-sugar-spice-cookbook/?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+BojonGourmet+%28The+Bojon+Gourmet%29
:sample_title: Coffee, Cinnamon & Muscovado Sugar Flans
