---
:root: bonappetit.com
:selector: article
:trimmers:
- ul.social-icons__list
:grammar_mods:
  :rp_inglist:
    :in_css_match: div.List-XYTyX
  :rp_ingline:
    :at_css_match: p.BaseWrap-sc-TURhJ
  :rp_title:
    :in_css_match: h1
  :rp_instructions:
    :in_css_match: div.InstructionsWrapper-guTAnx div
:sample_url: http://www.bonappetit.com/recipe/shaved-cauliflower-salad
:sample_title: Shaved Cauliflower Salad
