---
:root: cooking.nytimes.com
:selector: article.recipe-detail-card
:trimmers:
- div.nutrition-container
- div.secondary-controls
:grammar_mods:
  :rp_inglist:
    :in_css_match: ul.recipe-ingredients
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match:
:sample_url: http://cooking.nytimes.com/recipes/1016062-red-lentil-soup-with-lemon
:sample_title: Red Lentil Soup With Lemon
