---
:selector: |-
  h1
  div.body
  div[data-testid=IngredientList]
  div[data-testid=InstructionsWrapper]
:trimmers:
- div.mediavoice-native-ad
- div.additional-info
:grammar_mods:
  :rp_title:
    :in_css_match: h1
  :rp_inglist:
    :in_css_match: div.gPuEKn
  :rp_ingline:
    :in_css_match: div.eftAc
    :match_all: true
  :rp_instructions:
    :in_css_match: div.instructions ol
:sample_url: http://www.epicurious.com/recipes/food/views/apricot-tart-with-pistachio-almond-frangipane-106662
:sample_title: Apricot Tart with Pistachio-Almond Frangipane
