---
:selector: "div.heading\r\ndiv.chop-content\r\ndiv.featured-link-image\r\ndiv.relatedarticle-link"
:trimmers:
- div.mediavoice-native-ad
- div.additional-info
:grammar_mods:
  :rp_recipelist:
    :match: {}
  :rp_inglist:
    :in_css_match: ul.ingredients
  :rp_ingline:
    :in_css_match: li.ingredient
  :rp_title:
    :in_css_match: h1
  :rp_instructions:
    :in_css_match: div.instructions ol
