---
:selector: "div.heading\r\ndiv.chop-content\r\ndiv.featured-link-image\r\ndiv.relatedarticle-link"
:trimmers:
- div.mediavoice-native-ad
- div.additional-info
:grammar_mods:
  :rp_recipelist:
    :match: {}
  :rp_title:
    :in_css_match: h1
  :rp_instructions:
    :in_css_match: div.instructions ol
  :gm_inglist:
    :flavor: :unordered_list
    :list_class: ingredients
    :line_class: ingredient
