---
:root: everydayannie.com
:selector: |
  div.post-header
  div.recipe-bar
  div#ingredients
  div#directions ul
:trimmers:
- div.post-cat
- a.comments-number
- div.step-number
:grammar_mods:
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match:
  :gm_inglist:
    :flavor: :paragraph
    :paragraph_selector: div.ingredient-text p
:sample_url: http://everydayannie.com/2013/07/31/ginger-garlic-salmon-with-cabbage-salad/
:sample_title: Ginger Garlic Salmon with Cabbage Salad
