---
:selector: "div.post-header\r\ndiv.recipe-bar\r\ndiv#ingredients\r\ndiv#directions
  ul\r\n"
:trimmers:
- div.post-cat
- a.comments-number
- div.step-number
:grammar_mods:
  :rp_inglist:
    :in_css_match: div.ingredient-text p
  :rp_ingline:
    :in_css_match:
    :inline: true
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match:
