---
:root: everydayannie.com
:trimmers:
- div.post-cat
- a.comments-number
- div.step-number
:grammar_mods:
  :rp_inglist:
    :in_css_match: div.ingredient-text p
  :rp_ingline:
    :in_css_match:
    :inline: true
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match:
:sample_url: http://everydayannie.com/2013/07/31/ginger-garlic-salmon-with-cabbage-salad/
:sample_title: Ginger Garlic Salmon with Cabbage Salad - Everyday Annie
