---
:selector: div.main-content
:trimmers:
- div.article-gallery
- h6
- a.btn-large
:grammar_mods:
  :rp_recipelist:
    :match: {}
  :rp_inglist:
    :in_css_match: div.ingredients ul
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match: div.instructions
