---
:root: fantasticfungi.com
:trimmers:
- div.article-gallery
- h6
- a.btn-large
:grammar_mods:
  :rp_recipelist:
    :match: {}
  :rp_inglist:
    :in_css_match: div.ingredients ul
  :rp_ingline: {}
  :rp_title: {}
:sample_url: https://fantasticfungi.com/cookbook-recipes/white-bean-and-autumn-mushroom-dip/
:sample_title: White Bean and Autumn Mushroom Dip
