---
:selector: div.main-content
:trimmers:
- div.article-gallery
- h6
- a.btn-large
:grammar_mods:
  :gm_inglist:
    :flavor: :unordered_list
    :list_selector: div.ingredients ul
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match: div.instructions
:sample_url: https://fantasticfungi.com/cookbook-recipes/white-bean-and-autumn-mushroom-dip/
:sample_title: White Bean and Autumn Mushroom Dip
