---
:root: flybyjing.com
:selector: article
:trimmers:
- div.page__teeth
- div.colorful__teeth
- picture
:grammar_mods:
  :gm_inglist:
    :flavor: :paragraph
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match: ol
:sample_url: https://flybyjing.com/blog/recipe-the-best-vegan-mapo-tofu/
:sample_title: 'RECIPE: THE BEST VEGAN MAPO TOFU EVER'
