---
:selector: div.articleContainer
:trimmers:
- div.articleContainer__rail
- div.docked-sharebar
- div.lazy-image
:grammar_mods:
  :rp_recipelist:
    :match:
      :at_css_match: h2
  :rp_inglist:
    :in_css_match: ul
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h2
  :rp_instructions:
    :in_css_match:
