---
:root: foodandwine.com
:selector: div.content
:trimmers:
- div.articleContainer__rail
- div.docked-sharebar
- div.lazy-image
:grammar_mods:
  :gm_inglist:
    :flavor: :unordered_list
    :list_class: ingredients-section
    :line_class: ingredients-item
  :rp_title:
    :in_css_match: h1.headline
  :rp_instructions:
    :in_css_match:
:sample_url: http://www.foodandwine.com/recipes/stuffed-kale-with-bulgur-tabbouleh-and-lime-yogurt-dip
:sample_title: Stuffed Kale with Bulgur Tabbouleh and Lime Yogurt Dip
