---
:selector: "h1.recipe__title\r\ndiv.recipe__list--ingredients\r\ndiv.recipe__list--steps"
:trimmers: []
:grammar_mods:
  :rp_recipelist:
    :match: {}
  :rp_inglist:
    :in_css_match: div.recipe__list ul
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h1.recipe__title
  :rp_instructions:
    :in_css_match: div.recipe__list--steps ol
