---
:root: food52.com
:selector: |-
  header.recipe__header
  div.recipe__list--ingredients
  div.recipe__list--steps
:trimmers: []
:grammar_mods:
  :rp_title:
    :in_css_match: h1.recipe__title
  :rp_inglist:
    :in_css_match: div.recipe__list--ingredients ul
  :rp_ingline:
    :in_css_match: li
  :rp_instructions:
    :in_css_match: div.recipe__list--steps ol
:sample_url: https://food52.com/recipes/18008-ignacio-mattos-grilled-favas
:sample_title: Ignacio Mattos’ Grilled Favas
