---
:root: food52.com
:trimmers: []
:grammar_mods:
  :rp_recipelist:
    :match: {}
  :rp_inglist:
    :in_css_match: div.recipe__list ul
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h1.recipe__title
  :rp_instructions:
    :in_css_match: div.recipe__list--steps ol
:sample_url: http://food52.com/blog/3743_ignacio_mattoss_grilled_favas
:sample_title: Ignacio Mattos’s Grilled Favas
