---
:selector: div.recipe-extras
:trimmers:
- img
- h3 a
:grammar_mods:
  :rp_inglist:
    :in_css_match: ul.ingredients
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h3
  :rp_instructions:
    :in_css_match: ol.instructions
