---
:root: liquor.com
:selector: div.heading, div.article__content
:trimmers:
- div.inline-video
- div.feedback-block
- div.article-intro
- div.mntl-sc-block-featuredlink
- div.disqus-block
- header.section__header
:grammar_mods:
  :gm_inglist:
    :flavor: :unordered_list
    :list_class: structured-ingredients__list, ingredient-list
    :line_class: structured-ingredients__list-item, ingredient
    :paragraph_selector: ''
  :rp_instructions:
    :in_css_match: section.section--instructions ol
  :rp_title:
    :in_css_match: h1,h2,h3
  :gm_bundles: :no_bundle
  :rp_inglist:
    :in_css_match:
  :rp_ingline:
    :in_css_match:
  :rp_paragraph:
    :in_css_match:
:sample_url: https://www.liquor.com/recipes/navy-grog/
:sample_title: Navy Grog
