---
:root: www.liquor.com
:selector: div.heading, div.chop-content
:trimmers:
- div.inline-video
- div.feedback-block
- div.article-intro
- div.mntl-sc-block-featuredlink
- div.disqus-block
- header.section__header
:grammar_mods:
  :gm_recipes:
    :at_css_match: h1
  :gm_inglist:
    :flavor: :unordered_list
    :list_class: ingredient-list
    :line_class: ingredient
  :rp_instructions:
    :in_css_match: section.section--instructions
:sample_url: https://www.liquor.com/recipes/navy-grog/
:sample_title: Navy Grog
