---
:root: www.moodymixologist.com
:selector: |-
  ul.wprm-recipe-ingredients
  div.wprm-recipe
:trimmers:
- div.wprm-template-chic-buttons
:grammar_mods:
  :gm_bundles:
    :name: :wordpress
  :rp_title:
    :in_css_match: h2.wprm-recipe-name
:sample_url: https://www.moodymixologist.com/blog/the-saturn-a-tiki-cocktail-with-gin
:sample_title: The Saturn – Gin Tiki Cocktail
