---
:root: nutritionaction.com
:selector: article.grid-container
:trimmers:
- div.wprm-entry-footer
- div.social
- div.wprm-container-float-right
:grammar_mods:
  :rp_title:
    :in_css_match: h2
  :gm_inglist: :unordered_list
:sample_url: https://www.nutritionaction.com/daily/healthy-recipes/three-vegetable-sides-perfect-for-the-holiday-season/
:sample_title: Cauliflower with Lemon-Pine Nut Dressing
