---
:selector: div.entry-content
:trimmers:
- div.wprm-entry-footer
- div.social
- div.wprm-container-float-right
:grammar_mods:
  :gm_inglist: :paragraph
:sample_url: https://www.nutritionaction.com/daily/healthy-recipes/three-vegetable-sides-perfect-for-the-holiday-season/
:sample_title: Cauliflower with Lemon-Pine Nut Dressing
