---
:selector: "div.title-container\r\ndiv.recipe-instructions"
:trimmers:
- div.nutrition-container
- div.secondary-controls
:grammar_mods:
  :rp_inglist:
    :in_css_match: ul.recipe-ingredients
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match:
