---
:root: ruhlman.com
:trimmers: []
:grammar_mods:
  :rp_inglist:
    :in_css_match: ul
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h2
  :rp_instructions:
    :in_css_match:
:sample_url: http://ruhlman.com/2009/10/how-to-cure-olives/
:sample_title: How To Cure Olives
