---
:root: www.seriouseats.com
:trimmers:
- div.nav-share
- div.pubmod-date
- figure
- div.author-byline
- div.recipe-procedure-number
- div.recipe-procedures h2
:grammar_mods:
  :rp_recipelist:
    :match:
      :at_css_match: section.entry-container
  :rp_inglist:
    :in_css_match: div.recipe-ingredients ul
  :rp_ingline:
    :in_css_match: li.ingredient
  :rp_title:
    :in_css_match: h1
:sample_url: http://www.seriouseats.com/recipes/2010/04/fish-fragrant-eggplant-recipe-fuchsia-dunlop.html
:sample_title: 'Dinner Tonight: Fish Fragrant Eggplant'
