---
:root: seriouseats.com
:selector: div.article__container
:trimmers:
- div.nav-share
- div.mntl-tooltip
- div.recipe-decision__header
- div.mntl-sc-block-adslot
- div.project-meta-content
- button.button--save-recipe
- div.ads-config
- div.article-meta__byline-container
- div.jump-btn-wrapper
- div.social-share-wrapper
- nav.tag-nav
- div.pubmod-date
- figure
- div.author-byline
:grammar_mods:
  :gm_inglist:
    :flavor: :unordered_list
    :list_class: ingredient-list, structured-ingredients__list
    :line_class: ingredient, structured-ingredients__list-item
  :rp_title:
    :in_css_match: h1.heading__title
  :gm_bundles: :no_bundle
  :rp_inglist:
    :in_css_match:
  :rp_ingline:
    :in_css_match:
  :rp_instructions:
    :in_css_match: ol.mntl-sc-block-startgroup
  :rp_paragraph:
    :in_css_match:
:sample_url: http://www.seriouseats.com/recipes/2010/04/fish-fragrant-eggplant-recipe-fuchsia-dunlop.html
:sample_title: Fish-Fragrant Eggplants (Sichuan Braised Eggplant With Garlic, Ginger,
  and Chiles) Recipe
