---
:root: seriouseats.com
:selector: div.article__container
:trimmers:
- div.nav-share
- div.pubmod-date
- figure
- div.author-byline
:grammar_mods:
  :gm_inglist:
    :flavor: :unordered_list
    :list_class: structured-ingredients__list
    :line_class: structured-ingredients__list-item
  :rp_title:
    :in_css_match: h1.heading__title
:sample_url: http://www.seriouseats.com/recipes/2010/04/fish-fragrant-eggplant-recipe-fuchsia-dunlop.html
:sample_title: Fish-Fragrant Eggplants (Sichuan Braised Eggplant With Garlic, Ginger, and Chiles) Recipe
