---
:root: www.sfchronicle.com
:trimmers:
- section.relatedStories
- div.inDepth
- div.articleFooter
:grammar_mods: {}
:sample_url: http://www.sfchronicle.com/recipes/article/Preserving-tradition-with-DIY-tofu-4615283.php
:sample_title: Preserving tradition with DIY tofu
