---
:root: sfchronicle.com
:selector: article.article--content
:trimmers:
- section.relatedStories
- div.inDepth
- div.articleFooter
:grammar_mods:
  :gm_inglist: :unordered_list
  :rp_title:
    :in_css_match: div.recipe h3
:sample_url: http://www.sfchronicle.com/recipes/article/Preserving-tradition-with-DIY-tofu-4615283.php
:sample_title: Homemade Block Tofu
