---
:root: shesimmers.com
:selector: div.easyrecipe
:trimmers: []
:grammar_mods:
  :gm_inglist:
    :flavor: :unordered_list
    :list_selector: div.ERSIngredients ul
    :line_class: ingredient
  :rp_title:
    :in_css_match: div.ERSName
  :rp_instructions:
    :in_css_match: ol
:sample_url: http://shesimmers.com/2013/02/baked-salmon-in-lime-coconut-cream-sauce-%e0%b8%9b%e0%b8%a5%e0%b8%b2%e0%b9%81%e0%b8%8b%e0%b8%a5%e0%b8%a1%e0%b8%ad%e0%b8%99%e0%b8%ad%e0%b8%9a%e0%b8%81%e0%b8%b0%e0%b8%97%e0%b8%b4.html
:sample_title: Baked Salmon in Lime-Coconut Cream Sauce
