---
:root: www.simonmajumdar.com
:selector: div#comp-inhsovxx
:trimmers: []
:grammar_mods: {}
:sample_url: https://www.simonmajumdar.com/fiery-hot-lime-pickle
:sample_title: Simon Majumdar - Fiery Hot Lime Pickle
