---
:selector: div.recipe-callout
:trimmers:
- div.recipe-callout-buttons
- p.dont-steal
:grammar_mods:
  :triggers:
    :rp_author: Source
    :rp_yield:
    - Makes
    - Yield
  :rp_inglist:
    :in_css_match: ul
  :rp_ingline:
    :in_css_match: li.ingredient
  :rp_title:
    :in_css_match: h2
:sample_url: http://www.simplyrecipes.com/recipes/red_lentil_dal/
:sample_title: Red Lentil Dal Recipe | Simply Recipes
