---
:root: simplyrecipes.com
:selector: div.article__content
:trimmers:
- div.recipe-callout-buttons
- p.dont-steal
:grammar_mods:
  :triggers:
    :rp_author: Source
    :rp_yields:
    - Makes
    - Yield
  :gm_inglist:
    :flavor: :unordered_list
    :list_class: structured-ingredients__list
    :line_class: structured-ingredients__list-item
  :rp_title:
    :in_css_match: h2.recipe-block__header
:sample_url: http://www.simplyrecipes.com/recipes/red_lentil_dal/
:sample_title: Red Lentil Dal
