---
:root: skillet.lifehacker.com
:selector: |-
  div.js_post-content
  header h1
:trimmers:
- div.img-wrapper
- div.fIUNXF
- div.movable-ad
- div.content-summary__SummaryBox
- aside.inset--story
:grammar_mods: {}
:sample_url: https://skillet.lifehacker.com/celebrate-negroni-week-with-this-amaro-heavy-offering-1826676965
:sample_title: Celebrate Negroni Week With This Amaro-Heavy Offering
