---
:selector: div.dcr-hujbr5
:trimmers:
- div.meta__extras
- div.js-ad-slot
- figure[itemprop="associatedMedia image"]
- div.submeta
:grammar_mods:
  :rp_recipelist:
    :match:
      :at_css_match: h2
  :rp_recipe:
    :at_css_match: h2
  :rp_title:
    :in_css_match: h2
  :gm_inglist: :paragraph
