---
:root: thehappyfoodie.co.uk
:selector: article
:trimmers:
- div.page__teeth
- div.colorful__teeth
- picture
:grammar_mods:
  :rp_inglist:
    :in_css_match: ul
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match: ol
:sample_url: https://thehappyfoodie.co.uk/recipes/ottolenghis-brussels-sprouts-with-burnt-butter-and-black-garlic
:sample_title: Ottolenghi Brussels Sprouts Recipe | Saturday Kitchen
