---
:root: www.themediterraneandish.com
:selector: div#comp-inhsovxx
:trimmers: []
:grammar_mods: {}
:sample_url: https://www.themediterraneandish.com/vegetarian-moussaka-recipe/print/33043/
:sample_title: BEST Vegetarian Moussaka Recipe | The Mediterranean Dish
