---
:selector: article.article div.l-container
:trimmers:
- ul.tag-nav__list
- ul.social-nav__list
- div.figure__media
- div.aggregate-star-rating
- figure
- div.section-header
- div.nutrition-info
- div.decision-block__feedback
- div.article-header__media
- div.mntl-bio-tooltip__bottom
- div.mntl-bio-tooltip__top
- div.article-updated-date
- div.feedback-block
- div.inline-block
- div.inline-video
- div.featured-link
- div.sources
:grammar_mods:
  :rp_recipelist:
    :match:
      :at_css_match: h1
  :rp_ingline:
    :inline:
    :in_css_match: li
  :rp_inglist:
    :in_css_match: ul.ingredient-list
    :inline:
  :rp_title:
    :in_css_match: h1
  :rp_instructions:
    :in_css_match: div.structured-project__steps ol
