---
:root: thewoksoflife.com
:trimmers:
- div.wprm-entry-footer
- div.social
- div.wprm-container-float-right
:grammar_mods:
  :gm_recipes:
    :in_css_match: div.wprm-recipe-the-woks-of-life
  :rp_title:
    :in_css_match: h2
:sample_url: https://thewoksoflife.com/simple-spicy-pan-fried-noodles/
:sample_title: Simple, Spicy Pan-Fried Noodles
