---
:root: umamimart.com
:trimmers: []
:grammar_mods:
  :rp_recipelist:
    :match:
      :at_css_match: h3
  :rp_inglist:
    :in_css_match: p
  :rp_ingline: {}
  :rp_title:
    :in_css_match: h3
:sample_url: https://umamimart.com/blogs/main/the-pdt-project-aviation
:sample_title: 'The PDT Project: Aviation – Umami Mart'
