---
:root: vegkitchen.com
:selector: article.entry
:trimmers: []
:grammar_mods:
  :rp_inglist:
    :in_css_match: ul
  :rp_ingline:
    :in_css_match: li
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match:
:sample_url: http://www.vegkitchen.com/recipes/sesame-noodles-with-asparagus-tips/
:sample_title: Sesame Noodles with Asparagus Tips
