---
:root: afeast.wordpress.com
:selector: div.post-content
:trimmers:
- div#jp-post-flair
:grammar_mods:
  :rp_recipelist:
    :match: {}
  :gm_inglist:
    :flavor: :unordered_list
    :list_selector: p
  :rp_title:
    :in_css_match: h1,h2
  :rp_instructions:
    :in_css_match:
:sample_url: http://afeast.wordpress.com/2012/09/22/carrot-salad/
:sample_title: Carrot Salad
